name: 'Digital Studio Operations Terraform Action'
description: 'Validate, Plan and Deploy Terraform Code'
author: 'ministryofjustice'
branding:
  icon: 'wind'
  color: 'blue'
inputs:
  apply-on-default-branch-only:
    required: false
    default: 'true'
    description: If this flag is set to false it will run terraform apply on any branch, if it's true only on the default branch, normally main/master
  apply-on-pull-request:
    required: false
    default: 'false'
    description: If this flag is set to true it will run terraform apply on the pull_request event, e.g. if you want to the run tests on the deployed infra
  detect-drift:
    required: false
    default: 'false'
    description: If this flag is set to true the return code of terraform plan will be an output of the action.
  github-token:
    required: false
    description: 'Github Token should just generally be secrets.GITHUB_TOKEN'
  terraform-output-as-comment:
    required: false
    default: 'true'
    description: 'If set to true, the plan and apply outputs will be added as a comment to the pr'
  validate:
    required: false
    default: 'true'
    description: 'If set to true, it will run terraform validate on the working-directory'
  working-directory:
    required: false
    description: 'Directory for the Terraform files, if not specified it will run from current directory'
outputs:
  terraform-plan-return-code:
    description: This is the output of the terraform plan command. Only set if detect-drift is set to true
runs:
  using: 'node12'
  main: 'dist/index.js'
