name: "build"
on: # rebuild any PRs and main branch changes
  pull_request_target:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all
  automate-pullrequest-review:
    if: contains(github.event.pull_request.labels.*.name, 'dependencies') && (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Approve pull request
        uses: hmarr/auto-approve-action@5d04a5ca6da9aeb8ca9f31a5239b96fc3e003029
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"